# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 664c6235027e2394a095d995f7fd5a325f9ec8223569fa2dd071572aee107c60e6d866abc43dbd9a3731638c34d0d578fdb5cc34bbad1bbb9827d12d594358da

test:
  secret_key_base: 20629de3c3fd05e0b025dd226455b5f8f71de93fa2d210d77465d063c8bc2de3151c5e8f5d8369c84614ae07738e7826b4a55d7192f166ddb23df0a9a004b233

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
